// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsuk1saSsvKrMDdkTXShOyRKG2J867nDQ',
    appId: '1:807191222754:web:efdd7af078e37c919601bb',
    messagingSenderId: '807191222754',
    projectId: 'flutter-firebase-auth-3d466',
    authDomain: 'flutter-firebase-auth-3d466.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-3d466.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRhGCWC7HQNomsoSdMQIYgYeczu5APfc',
    appId: '1:807191222754:android:4d0440e6f7f9325c9601bb',
    messagingSenderId: '807191222754',
    projectId: 'flutter-firebase-auth-3d466',
    storageBucket: 'flutter-firebase-auth-3d466.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_M4870EjXza2gREosjU9cMh-IV4vDxsM',
    appId: '1:807191222754:ios:9bf05e2dd278c8099601bb',
    messagingSenderId: '807191222754',
    projectId: 'flutter-firebase-auth-3d466',
    storageBucket: 'flutter-firebase-auth-3d466.appspot.com',
    iosClientId: '807191222754-qf833maae8cjasnk40e9o6mipolig7a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_M4870EjXza2gREosjU9cMh-IV4vDxsM',
    appId: '1:807191222754:ios:9bf05e2dd278c8099601bb',
    messagingSenderId: '807191222754',
    projectId: 'flutter-firebase-auth-3d466',
    storageBucket: 'flutter-firebase-auth-3d466.appspot.com',
    iosClientId: '807191222754-qf833maae8cjasnk40e9o6mipolig7a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuth',
  );
}
